version: "3.9"

services:
  api_express:
    container_name: api_express
    image: node:16
    build: .
    ports:
      - 3001:3000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bryan
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=defaultdb  